#!/bin/sh
set -e
"$BASELOC"/o/cli/htop/htop*/configure --prefix="$COSMOS"\
    --enable-static --disable-fuzzing\
    --disable-dependency-tracking\
    --disable-utempter --disable-utf8proc\
    --disable-systemd\
    CFLAGS="-Os -I$COSMOS/include/ncurses -fno-strict-aliasing -Wno-unknown-pragmas -Wno-error=initializer-overrides -Wno-overlength-strings"\
    CPPFLAGS="-D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600"\
    LDFLAGS="-static"
