#!/bin/sh
set -e
# export STRIP="/bin/true"
# alias strip=$STRIP
# alias ar="$AR"

# why
pwd
ls -la
ls -a /ahgamut/superconfigure/o/cli/nethack/
cp -r "$BASELOC"/o/cli/nethack/NetHack*/* ./

sh sys/unix/setup.sh sys/unix/hints/linux


