#!/bin/sh
set -e

cp -r "$BASELOC"/o/games/nethack/NetHack*/* ./

sudo mkdir -p /zip/cfg

echo "debug" 
ls -la
cat sys/unix/hints/linux
patch -p0 -i "/home/runner/work/superconfigure/superconfigure/games/nethack/minimal_x86.diff"

sh sys/unix/setup.sh sys/unix/hints/linux
