#!/bin/sh
set -e

cp -r "$BASELOC"/o/games/nethack/NetHack*/* ./

sudo mkdir -p /zip/cfg

echo "debug"
ls -la
cat -n sys/unix/hints/linux | head -20
patch -p0 --fuzz=3 -i "/home/runner/work/superconfigure/superconfigure/games/nethack/minimal_aarch64.diff"

sh sys/unix/setup.sh sys/unix/hints/linux
