#!/bin/sh
set -ex

COSMO_ARCH=$1

cp -r "$BASELOC"/o/games/nethack/NetHack*/* ./

sed -i "s|^HACKDIR=.*|HACKDIR=/home/runner/work/superconfigure/superconfigure/cosmos/$COSMO_ARCH/bin/|" sys/unix/hints/linux
sed -i "s|SYSCONFDIR=.*|SYSCONFDIR=/home/runner/work/superconfigure/superconfigure/cosmos/$COSMO_ARCH|" sys/unix/hints/linux

sh sys/unix/setup.sh sys/unix/hints/linux
