#!/bin/sh
set -e

cp -r "$BASELOC"/o/games/nethack/NetHack*/* ./

COSMO_ARCH=$1

sed -i "s|HACKDIR=.*|HACKDIR=$COSMO_ARCH/bin/|" sys/unix/hints/linux
sed -i "s|SYSCONFDIR=.*|SYSCONFDIR=$COSMO_ARCH|" sys/unix/hints/linux

sh sys/unix/setup.sh sys/unix/hints/linux
