#!/bin/sh
set -ex

FILELIST='nethack'

cp "/home/runner/nh/install/games/lib/nethackdir/nethack" "$COSMOS_X86_64/bin/nethack"
cp "/home/runner/nh/install/games/lib/nethackdir/nethack/sysconf" "$COSMOS_X86_64/"
cp "/home/runner/nh/install/games/lib/nethackdir/nethack/nhdat" "$COSMOS_X86_64/"  

cp "/home/runner/nh/install/games/lib/nethackdir/nethack" "$COSMOS_AARCH64/bin/nethack"
cp "/home/runner/nh/install/games/lib/nethackdir/nethack/sysconf" "$COSMOS_AARCH64/"
cp "/home/runner/nh/install/games/lib/nethackdir/nethack/nhdat" "$COSMOS_AARCH64/"

apelinkpls () {
    OUTPUT="$1"
    OLDNAME_X86_64="$(basename -- "$2")"
    OLDNAME_AARCH64="$(basename -- "$3")"
    TARG_FOLD="$(dirname "$OUTPUT")"
    cp "$2" "$TARG_FOLD/$OLDNAME_X86_64.x86_64"
    cp "$3" "$TARG_FOLD/$OLDNAME_AARCH64.aarch64"
    "$RENAMESTR" -f "$COSMOS_X86_64" -t "/zip" \
        -f "$COSMOS_AARCH64" -t "/zip" \
        "$TARG_FOLD/$OLDNAME_X86_64.x86_64"
    "$RENAMESTR" -f "$COSMOS_X86_64" -t "/zip" \
        -f "$COSMOS_AARCH64" -t "/zip" \
        "$TARG_FOLD/$OLDNAME_AARCH64.aarch64"
    "$APELINK" -l "$COSMO/o/x86_64/ape/ape.elf" \
        -l "$COSMO/o/aarch64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$TARG_FOLD/$OLDNAME_X86_64.x86_64"\
        "$TARG_FOLD/$OLDNAME_AARCH64.aarch64"
}

for EXE in $FILELIST; do

	apelinkpls "$RESULTS"/bin/"$EXE".com "$COSMOS_X86_64"/bin/"$EXE" "$COSMOS_AARCH64"/bin/"$EXE"
	echo "adding zip assets from x86_64 to $EXE"
	cd "$COSMOS_X86_64"
	zip -qr "$RESULTS"/bin/"$EXE".com \
		share/terminfo \
		sysconf \
		nhdat 

	echo "adding zip assets from aarch64 to $EXE"
	cd "$COSMOS_AARCH64"
	zip -qr "$RESULTS"/bin/"$EXE".com \
		share/terminfo \
		sysconf \
		nhdat

	cd "$BASELOC"
done
