name: Build Cosmo

on:
  workflow_dispatch:

jobs:
  build-cosmo:
    runs-on: ubuntu-latest
    needs: prepare-ubuntu

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Build Cosmo
        working-directory: /ahgamut/superconfigure
        run: bash ./.github/scripts/cosmo
