name: Prepare Ubuntu

on:
  workflow_dispatch:

jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and upgrade Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential
          sudo apt-get install -y curl
          sudo apt-get install -y wget
          sudo apt-get install -y git
